html-form
AndresR9707/html-tutorial pull request #6
Opened 2020-12-22 02:22 UTC by AndresR9707

2020-12-23 15:35 UTC, fabianmarinog requested changes
Good job. The general exercise is correctly implemented, just check these comments.

2020-12-23 15:35 UTC, fabianmarinog commented on form.html
> +    <title>Ferreteria Trinidad</title>
the order doesn't matter but for readability the `<title>` comes first.

2020-12-23 15:35 UTC, fabianmarinog commented on form.html
> +    <button type="reset" id="btn_reset">Eliminar</button>
this should be 
```suggestion
    <button type="reset" id="btn_reset">Cancelar</button>   
```

2020-12-23 15:35 UTC, fabianmarinog commented on form.html
> +    <label id="information">Mayor Informacion:</label>
`<label>` is more common within `<form>` and `<input>` Use `<p>`
```suggestion
    <p>Mayor Informacion:</p>
```

2020-12-23 15:35 UTC, fabianmarinog commented on form.html
> +      <li>Cr 14 # 1 A sur Tunja(Boyaca)</li>
```suggestion
      <li><address>Cr 14 # 1 A sur Tunja(Boyaca)</address></li>
```

2020-12-23 15:39 UTC, fabianmarinog requested changes

2020-12-23 15:39 UTC, fabianmarinog commented on form.html
> +      </label>
```suggestion
 <strong>Medios de pago:</strong>
      <abbr title="required" aria-label="required">*</abbr><br>   
        <label for="cash">Efectivo:<input type="radio" id="cash" name="method" required></label><br> 
       <label for="card">Tarjeta:<input type="radio" id="card" name="method" required></label><br>
       <label for="pse">PSE:<input type="radio" id="pse" name="method" required></label><br>
```

2021-01-05 21:36 UTC, pushdev-code requested changes
just one final comment

2021-01-05 21:36 UTC, pushdev-code commented on form.html
> +      <p>Realiza tus pedidos:</p>
```suggestion
      <h3>Realiza tus pedidos:</h3>
```
The section needs a heading and this one is the best to meet that requirement.

2021-01-07 17:00 UTC, merged